
name: jazzy_vnc

on:
  workflow_dispatch:
    inputs:
      org:
        type: string
        description: Docker organization
        required: true
        default: 'jenoch'
      name:
        type: string
        description: Docker image name
        required: true
        default: 'jazzy_vnc'
      tag:
        type: string
        description: Docker image tag
        required: true
      latest:
        type: boolean
        description: Also tag as "latest"
        required: true
        default: true

env:
  DOCKER_IMAGE_AMD64: ${{ github.event.inputs.org }}/${{ github.event.inputs.name}}-amd64:${{ github.event.inputs.tag }}
  DOCKER_IMAGE_ARM64: ${{ github.event.inputs.org }}/${{ github.event.inputs.name}}-arm64:${{ github.event.inputs.tag }}
  DOCKER_IMAGE_FINAL: ${{ github.event.inputs.org }}/${{ github.event.inputs.name}}:${{ github.event.inputs.tag }}
  DOCKER_IMAGE_LATEST: ${{ github.event.inputs.org }}/${{ github.event.inputs.name}}:latest

jobs:
  docker-build-amd64:
    name: Docker AMD64 build and push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push AMD64 image
        run: |
          set -xe
          docker build docker -f docker/Dockerfile -t ${{ env.DOCKER_IMAGE_AMD64 }} --no-cache --platform linux/amd64
          docker push ${{ env.DOCKER_IMAGE_AMD64 }}

  docker-build-arm64:
    name: Docker ARM64 build and push
    runs-on: 	ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push ARM64 image
        run: |
          set -xe
          docker build docker -f docker/Dockerfile -t ${{ env.DOCKER_IMAGE_ARM64 }} --no-cache --platform linux/arm64/v8
          docker push ${{ env.DOCKER_IMAGE_ARM64 }}

  docker-build-manifest:
    name: Docker manifest build and push
    needs: [docker-build-amd64, docker-build-arm64]
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Pull the latest images for both architectures
        run: |
          set -xe
          docker pull ${{ env.DOCKER_IMAGE_AMD64 }}
          docker pull ${{ env.DOCKER_IMAGE_ARM64 }}

      - name: Create and push Docker manifest
        run: |
          set -xe
          docker manifest create --amend ${{ env.DOCKER_IMAGE_FINAL }} \
            ${{ env.DOCKER_IMAGE_AMD64 }} \
            ${{ env.DOCKER_IMAGE_ARM64 }}
          docker manifest push ${{ env.DOCKER_IMAGE_FINAL }}

      - name: Tag and push as latest
        if: ${{ inputs.latest }}
        run: |
          set -xe
          docker manifest rm ${{ env.DOCKER_IMAGE_LATEST }} || true
          docker manifest create ${{ env.DOCKER_IMAGE_LATEST }} \
            ${{ env.DOCKER_IMAGE_AMD64 }} \
            ${{ env.DOCKER_IMAGE_ARM64 }}
          docker manifest push ${{ env.DOCKER_IMAGE_LATEST }}
